modbus-pipeline:
  workers: 20 # the number of workers
  delay: 10 # in milliseconds, how long workers wait between read attempts
  source:
    http:
      ssl: false
      port: 2021
      thread_count: 500
      max_connection_count: 2000
      request_timeout: 10000
  buffer:
    bounded_blocking:
      buffer_size: 2000000 # max number of events the buffer will accept
      batch_size: 100 # max number of events the buffer will drain for each read
  route:
    - infra-logs: '/ingest_type == "monitor"'
    - infra-state: '/ingest_type == "state"'
  sink:
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        insecure: true
        username: admin
        password: ABCDeFghe1
        index: infra_all_logs
        routes: [infra-logs]
    - opensearch:
        hosts: ["http://opensearch-node1:9200"]
        insecure: true
        username: admin
        password: ABCDeFghe1
        index: infras
        routes: [infra-state]
